---
title: "Knowledge Consumed"
date: 2018-09-05
---
title:Jiheng's Blog
author: Jiheng Chen
email: chenjiheng1996@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is about the skillsets that I have learned during this semester!

# social links

github_username:  chenjiheng1996

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
